[package]
name = "year_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
aoclib = { path = "../aoclib" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "aoc_benchmark"
harness = false
