[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
default-run = "aoc"

[lib]
name = "utils"
path = "src/lib/mod.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
md5 = "0.7.0"
itertools = "0.8"
