[package]
name = "year_2015"
version = "0.1.0"
edition = "2021"

[dependencies]
aoclib = { path = "../aoclib" }
md5 = "0.7.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "aoc_benchmark"
harness = false
